steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '--file', './dockerfiles/train_model.dockerfile', '-t', 'gcr.io/firm-catalyst-410709/piano-video-train', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '--file', './dockerfiles/predict_model.dockerfile', '-t', 'gcr.io/firm-catalyst-410709/piano-video-predict', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/firm-catalyst-410709/piano-video-train']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/firm-catalyst-410709/piano-video-predict']