hyperparameters:
  dim: 64                       # number of U-net channels
  dim_mults: [1, 2, 4, 8]       # channel multiplication in U-net
  flash_attn:  True
  image_size: 128
  timesteps: 1000               # number of steps
  sampling_timesteps: 250       # number of sampling timesteps
  train_batch_size: 16
  train_lr: 8e-5                # learning rate
  train_num_steps: 1000         # total training steps
  gradient_accumulate_every: 2  # gradient accumulation steps
  ema_decay: 0.995              # exponential moving average decay
  amp: False                    # turn on mixed precision (if True training breaks on Apple Silicon Macs)
  calculate_fid: False          # whether to calculate fid during training
  num_fid_samples: 50           # how much samples to use for fid calculation
  save_and_sample_every: 250    # when to save model and generated samples
  seed: 44                      # for setting manual seed
  image_nos_to_generate: 1      # number of images to generate in predict
logging:
  log_on : True                 # set to false to diasble wandb and tensorboard logging