hyperparameters:
  dim: 64                      # number of U-net channels
  dim_mults: [1, 2, 4, 8]      # channel multiplication in U-net
  flash_attn:  True
  image_size: 64
  timesteps: 1000              # number of steps
  sampling_timesteps: 250      # number of sampling timesteps
  train_batch_size: 8
  train_lr: 8e-5               # learning rate
  train_num_steps: 100         # total training steps
  gradient_accumulate_every: 2 # gradient accumulation steps
  ema_decay: 0.995             # exponential moving average decay
  amp: True                    # turn on mixed precision
  calculate_fid: True          # whether to calculate fid during training
  num_fid_samples: 50          # how much samples to use for fid calculation
  save_and_sample_every: 1000  # when to save model and generated samples